[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:149 There was an error managing chromedriver (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)); using driver found in the cache
[32mINFO    [0m D:\QA\RAFT_TDD_UI\SupportLibraries\ui_helpers.py - 	LN:22:ui_helpers.py:195 Element found with locator_properties: //input[@placeholder='Username'] and locator_type: xpath
[32mINFO    [0m D:\QA\RAFT_TDD_UI\SupportLibraries\ui_helpers.py - 	LN:22:ui_helpers.py:303 Sent data to the element with locator_properties: //input[@placeholder='Username'] and locator_type: xpath