[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253051B7770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7e5a2a59086eebb89759cfe562dd6222/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253051B7B30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7e5a2a59086eebb89759cfe562dd6222/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253051B40B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7e5a2a59086eebb89759cfe562dd6222/screenshot